"""empty message

Revision ID: 4f67021f2d30
Revises: 68588ce85ba3
Create Date: 2019-10-31 10:02:43.202524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f67021f2d30'
down_revision = '68588ce85ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('api_key', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'usuario', ['api_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_column('usuario', 'api_key')
    # ### end Alembic commands ###
