"""empty message

Revision ID: 68588ce85ba3
Revises: 79a61dbc5c21
Create Date: 2019-10-30 09:28:59.217248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68588ce85ba3'
down_revision = '79a61dbc5c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'is_admin')
    # ### end Alembic commands ###
